server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
    session:
      timeout: 30

spring:
  data:
    mongodb:
      host: localhost
      port: 20000
      database: greendb